blank_issues_enabled: false
contact_links:
  - name: Community Discussions & Q/A
    url: https://github.com/abdullahsajid0/MeterReaderflutter/discussions
    about: Ask general questions, request advice, discuss electricity tariffs, or share your thoughts with the community.
